/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Interfaces.I_MESI_Cache;
import Logic.MESI_Model;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import static javax.swing.BorderFactory.createLineBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Vasiliy
 */
public class MainFrame extends javax.swing.JFrame {

    private ArrayList<JTable> CacheTables;
    private ArrayList<JScrollPane> CacheScrollPanes;
    int SelectedCacheNum;
    int SelectedMemoryString;
    MESI_Model Model;
    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        adjustColumnSizes(MemoryTable, 0, 2);
        CacheTables = new ArrayList<>(6);
        CacheScrollPanes = new ArrayList<>(6);
        SelectedCacheNum = -1;
        CacheComboBox.addActionListener (new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                SelectCache(((JComboBox)e.getSource()).getSelectedIndex());
            }
        });
        StringComboBox.addActionListener (new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                SelectMemoryString(((JComboBox)e.getSource()).getSelectedIndex());
            }
        });
        MemoryTable.getSelectionModel().addListSelectionListener(new ListSelectionListener () {

            @Override
            public void valueChanged(ListSelectionEvent e)
            {
               SelectMemoryString(((ListSelectionModel)e.getSource()).getMaxSelectionIndex());
            }
          
        });
         Model = new MESI_Model();
    }
    
    

    private class CacheTableMouseListener extends MouseAdapter{

        @Override
        public void mouseClicked(MouseEvent e)
        {
            SelectCache(CacheTables.indexOf((JTable)e.getSource()));
        }      
        
    }
    
    private class CacheScrollPaneMouseListener extends MouseAdapter{

        @Override
        public void mouseClicked(MouseEvent e)
        {
            SelectCache(CacheScrollPanes.indexOf((JScrollPane)e.getSource()));
        }      
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemoryTable = new javax.swing.JTable();
        NumberFormat format = NumberFormat.getInstance();
        format.setGroupingUsed(false);
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(1);
        formatter.setMaximum(Integer.MAX_VALUE);
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Cache_Num_Field = new javax.swing.JFormattedTextField(formatter);
        Mem_Size_Field = new javax.swing.JFormattedTextField(formatter);
        Cache_Size_Field = new javax.swing.JFormattedTextField(formatter);
        String_Size_Field = new javax.swing.JFormattedTextField(formatter);
        jPanel4 = new javax.swing.JPanel();
        CacheComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        StringComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CachePane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(492, 214));

        MemoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Номер", "Содержание"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        MemoryTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MemoryTable.getTableHeader().setReorderingAllowed(false);
        MemoryTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(MemoryTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(217, 161));

        jLabel1.setText("Число кэшей");

        jLabel2.setText("Размер памяти");

        jLabel3.setText("Размер кэша");

        jLabel4.setText("Размер строки");

        jButton1.setText("Иницализировать модель");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        Cache_Num_Field.setText("4");

        Mem_Size_Field.setText("12");

        Cache_Size_Field.setText("6");

        String_Size_Field.setText("64");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Cache_Num_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mem_Size_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cache_Size_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(String_Size_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Cache_Num_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Mem_Size_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cache_Size_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(String_Size_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(217, 178));

        jLabel5.setText("Выбор кэша");

        jLabel6.setText("<html>\nВыбор строки в памяти\n</html>");

        jButton2.setText("Считать");

        jButton3.setText("Инвалидировать");

        jLabel7.setText("Новое значение строки:");

        jButton4.setText("Записать");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CacheComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StringComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CacheComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StringComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.GridBagLayout CachePaneLayout = new java.awt.GridBagLayout();
        CachePaneLayout.columnWidths = new int[] {0};
        CachePaneLayout.rowHeights = new int[] {0};
        CachePane.setLayout(CachePaneLayout);
        jScrollPane2.setViewportView(CachePane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
       
        int Cache_Num = Integer.parseInt(this.Cache_Num_Field.getText());
        int Mem_Size = Integer.parseInt(this.Mem_Size_Field.getText());
        int Cache_Size = Integer.parseInt(this.Cache_Size_Field.getText());
        int String_Size = Integer.parseInt(this.String_Size_Field.getText());
        if (Cache_Size > Mem_Size)
        {
            JOptionPane.showMessageDialog(rootPane, "Размер кэша не может превышать размер памяти", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Model.Initialize(Cache_Num, Mem_Size, Cache_Size, String_Size);
        
        this.SetUpMemory();
        this.SetUpCaches();
        
        this.validate();
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SetUpMemory()
    {
        ((DefaultTableModel)this.MemoryTable.getModel()).setRowCount(Model.GetMemSize());
        StringComboBox.removeAllItems();
        for (int i=0;i<Model.GetMemSize();i++)
        {
            ((DefaultTableModel)this.MemoryTable.getModel()).setValueAt(i+1, i, 0);
            StringComboBox.addItem("Строка № " + String.valueOf(i+1));
        }
        adjustColumnSizes(MemoryTable, 0, 2);
        SelectMemoryString(0);
    }
    private void SetUpCaches()
    {
        ArrayList<I_MESI_Cache> Caches = Model.GetCaches();
        this.CachePane.removeAll();
        this.CacheTables.clear();
        this.CacheComboBox.removeAllItems();
        this.CacheScrollPanes.clear();
        for (int i=0; i<Model.GetCacheNum(); i++)
        {
            GridBagConstraints constraints = new GridBagConstraints();
            constraints.gridx = i%2;
            constraints.gridy = 2*(i/2);
            constraints.gridwidth = 1;
            constraints.gridheight = 1;
            constraints.weightx = 0;
            constraints.weighty = 0;
            constraints.fill = GridBagConstraints.HORIZONTAL;
            constraints.anchor = GridBagConstraints.NORTHWEST;
            JLabel Label = new JLabel("Кэш № " + String.valueOf(i+1));
            Label.setMaximumSize(Label.getPreferredSize());
            CachePane.add(Label,constraints);
            
          
            
            JTable CacheTable = new javax.swing.JTable();
            CacheTableModel Model = new CacheTableModel(0);
            Model.ExtractCacheData(Caches.get(0));
            CacheTable.setModel(Model);
            adjustColumnSizes(CacheTable, 0, 2);
            adjustColumnSizes(CacheTable, 1, 2);
            adjustColumnSizes(CacheTable, 2, 2);
            adjustColumnSizes(CacheTable, 3, 2);
            adjustTableSize(CacheTable);
            CacheTable.getTableHeader().setReorderingAllowed(false);
            CacheTable.setShowVerticalLines(true);
            CacheTable.addMouseListener(new CacheTableMouseListener());
            CacheTables.add(CacheTable);
            JScrollPane ScrollPane = new JScrollPane();
            //ScrollPane.setBorder(createLineBorder(Color.BLACK,1));
            ScrollPane.addMouseListener(new CacheScrollPaneMouseListener());
            CacheScrollPanes.add(ScrollPane);
            ScrollPane.add(CacheTable);
            ScrollPane.setViewportView(CacheTable);
            ScrollPane.setPreferredSize(new Dimension(CacheTable.getMaximumSize().width+20,
                    130));
            
            constraints.gridy = 2*(i/2)+1;
            constraints.weightx = 1;
            constraints.weighty = 1;
            constraints.fill = GridBagConstraints.BOTH;
            constraints.anchor = GridBagConstraints.NORTHWEST;
            
            CachePane.add(ScrollPane,constraints);
            
            CacheComboBox.addItem("Кэш № " + String.valueOf(i+1));
        }
        this.SelectCache(0);
    }
   private void adjustColumnSizes(JTable table, int column, int margin) {
        DefaultTableColumnModel colModel = (DefaultTableColumnModel) table.getColumnModel();
        TableColumn col = colModel.getColumn(column);
        int width;

        TableCellRenderer renderer = col.getHeaderRenderer();
        if (renderer == null) {
            renderer = table.getTableHeader().getDefaultRenderer();
        }
        Component comp = renderer.getTableCellRendererComponent(table, col.getHeaderValue(), false, false, 0, 0);
        width = comp.getPreferredSize().width;

        for (int r = 0; r < table.getRowCount(); r++) {
            renderer = table.getCellRenderer(r, column);
            comp = renderer.getTableCellRendererComponent(table, table.getValueAt(r, column), false, false, r, column);
            int currentWidth = comp.getPreferredSize().width;
            width = Math.max(width, currentWidth);
        }

        width += 2 * margin;

        col.setPreferredWidth(width);
        col.setMaxWidth(width);
    }
   private void adjustTableSize(JTable table) {
        DefaultTableColumnModel colModel = (DefaultTableColumnModel) table.getColumnModel();
        int MaxWidth  = 0;
        int PreferredWidth  = 0;
        for (int i=0;i<colModel.getColumnCount();i++)
        {
            MaxWidth +=colModel.getColumn(i).getMaxWidth();
            PreferredWidth +=colModel.getColumn(i).getPreferredWidth();
        }
        table.setPreferredSize(new Dimension(PreferredWidth,table.getPreferredSize().height));
    }
   
   private void SelectCache(int Num)
   {
       if ((SelectedCacheNum != Num) && (Num != -1))
       {
           if (SelectedCacheNum != -1)
           {
               CacheScrollPanes.get(SelectedCacheNum).setBorder(createLineBorder(Color.BLACK,1));
           }
           SelectedCacheNum = Num;
           CacheScrollPanes.get(SelectedCacheNum).setBorder(createLineBorder(Color.BLACK,3));
           CacheComboBox.setSelectedIndex(Num);
       }
       
   }
   
    private void SelectMemoryString(int Num)
   {
       if ((SelectedMemoryString != Num) && (Num != -1))
       {
           SelectedMemoryString = Num;
           MemoryTable.setRowSelectionInterval(Num, Num);
           StringComboBox.setSelectedIndex(Num);
       }
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CacheComboBox;
    private javax.swing.JPanel CachePane;
    private javax.swing.JFormattedTextField Cache_Num_Field;
    private javax.swing.JFormattedTextField Cache_Size_Field;
    private javax.swing.JFormattedTextField Mem_Size_Field;
    private javax.swing.JTable MemoryTable;
    private javax.swing.JComboBox StringComboBox;
    private javax.swing.JFormattedTextField String_Size_Field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
